export const siteCopy = {
  brand: {
    name: "WordTap",
    domain: ".cn",
    fullName: "WordTap.cn",
  },
  defaultText:
    "Learning English is easier when every word can speak for itself. " +
    "Paste an article here, split it into words, then click any word to hear it " +
    "and see its Chinese meaning.",
  metadata: {
    title: "WordTap.cn - 英语阅读点读查词工具｜听发音，看释义，读懂原文",
    description:
      "WordTap.cn 是一款面向英语阅读的点读查词工具。粘贴英文文章，点击单词即可听发音、看中文释义，在原文上下文里积累生词。",
    keywords: "英语阅读,英语查词,单词点读,英语精读,英文文章学习,单词发音,中文释义,生词学习,WordTap,WordTap.cn",
    ogTitle: "WordTap.cn - 英语阅读点读查词工具",
    ogDescription: "读英文时少一点切换和打断。粘贴文章，点击单词，听发音、看释义，把生词放回上下文里理解。",
    twitterTitle: "WordTap.cn - 英语阅读点读查词工具",
    twitterDescription: "为英文阅读和精读设计的点读查词工具：点击单词，听发音，看释义，保留原文上下文。",
    socialImageUrl: "https://wordtap.cn/demo.webp",
    socialImageType: "image/webp",
    socialImageAlt: "WordTap 点词阅读和查词界面预览",
    jsonLdDescription:
      "WordTap.cn 是一款面向英语阅读和精读练习的点读查词工具，帮助学习者在原文上下文里听单词发音、查看中文释义并积累生词。",
    featureList: [
      "粘贴英文文本并生成可点读文本",
      "点击单词听英文发音",
      "在阅读上下文中查看中文释义",
      "适合精读、跟读和生词理解",
      "用户粘贴的学习文本默认不上传",
    ],
    fallbackTitle: "WordTap.cn 英语阅读点读查词工具",
    fallbackDescription: "粘贴英文文章，点击单词听发音、看中文释义，并在原文上下文里积累生词。",
  },
  controls: {
    rateOptionLabels: {
      "-40%": "很慢",
      "-20%": "慢一点",
      "-10%": "稍慢",
      "+0%": "正常",
      "+10%": "稍快",
      "+20%": "快一点",
      "+40%": "很快",
    },
    translateModeOptions: [
      { value: "auto", label: "自动" },
      { value: "ecdict", label: "离线词典" },
      { value: "baidu_sug", label: "在线查词" },
    ],
    defaultGatewayVoice: "en-US-EmmaMultilingualNeural",
    gatewayVoiceOptions: [
      { value: "en-US-EmmaMultilingualNeural", label: "在线美式女声 Emma 多语言" },
      { value: "en-US-AvaNeural", label: "在线美式女声 Ava" },
      { value: "en-US-JennyNeural", label: "在线美式女声 Jenny" },
      { value: "en-US-AriaNeural", label: "在线美式女声 Aria" },
      { value: "en-US-EmmaNeural", label: "在线美式女声 Emma" },
      { value: "en-US-GuyNeural", label: "在线美式男声 Guy" },
      { value: "en-US-AndrewNeural", label: "在线美式男声 Andrew" },
      { value: "en-US-BrianNeural", label: "在线美式男声 Brian" },
      { value: "en-GB-LibbyNeural", label: "在线英式女声 Libby" },
      { value: "en-GB-SoniaNeural", label: "在线英式女声 Sonia" },
      { value: "en-GB-RyanNeural", label: "在线英式男声 Ryan" },
      { value: "en-GB-ThomasNeural", label: "在线英式男声 Thomas" },
    ],
    fallbackDictionary: {
      english: "n. 英语\nadj. 英语的；英国的",
      learning: "n. 学习\nv. 学习",
      word: "n. 单词；话语",
    },
  },
  state: {
    currentWordEmpty: "还没点单词",
    meaningHint: "点一下英文单词，就能听发音、看中文意思。",
    initialStatus: "粘贴英文后，就可以点词听读。",
    dictionaryPreparing: "正在准备查词...",
    cacheUnchecked: "还没检查",
  },
  computed: {
    wordCount: (count: number) => (count ? `${count} 个可点读单词` : "还没有英文单词"),
    textHistoryEmpty: (hasRecords: boolean) => (hasRecords ? "选择保存的文章" : "还没有保存的文章"),
    reviewEmpty: (hasRecords: boolean) =>
      hasRecords ? "没有找到匹配的单词。换个词试试。" : "还没有保存单词。开始阅读后，点过的单词会自动留在这里。",
    gatewayStatusReady: "可以全文朗读了",
    diagnosticsSummary: (ok: number, warn: number, fail: number) => `${ok} 项可用，${warn} 项提醒，${fail} 项需要处理`,
    studyReadyStatus: (hasText: boolean) => (hasText ? "点英文单词，就能听发音、看中文意思。" : "粘贴一段英文文本就可以开始点读。"),
  },
  status: {
    translateModeSelected: (label: string) => `已选择查词方式：${label}`,
    historyUnavailable: "学习记录暂时不可用，仍可继续点读查词。",
    textHistoryUnavailable: "保存的文章暂时不可用，仍可继续阅读。",
    restoredLatestArticle: (title: string) => `已恢复最近文章：${title}`,
    exampleLoaded: "已载入示例文本，可以直接点词体验。",
    readyToPaste: "粘贴一段英文文本就可以开始点读。",
    noArticleToSave: "没有可保存的文章。",
    articleSaved: (title: string) => `已保存文章：${title}`,
    articleSaveFailed: "文章保存失败。",
    articleLoaded: (title: string) => `已载入文章：${title}`,
    selectSavedArticleFirst: "请先选择一篇保存过的文章。",
    deleteArticleConfirm: (title: string) => `删除保存过的文章「${title}」？当前输入框内容不会被清空。`,
    articleDeleted: (title: string) => `已删除保存过的文章：${title}`,
    articleDeleteFailed: "删除文章失败。",
    deleteWordConfirm: (word: string) => `删除单词「${word}」？`,
    wordDeleted: (word: string) => `已删除单词：${word}`,
    wordListRefreshed: "单词列表已刷新。",
    noWordsToExport: "还没有单词可导出。",
    wordsExported: (count: number) => `已导出 ${count} 个单词。`,
    wordsImported: (count: number) => `已导入 ${count} 个单词。`,
    wordsImportFailed: "导入单词失败。",
    wordSelected: (word: string) => `已选择单词：${word}`,
    diagnosticsRunning: "正在检查功能状态...",
    diagnosticsDone: (summary: string) => `检查完成：${summary}`,
    translationCacheCleared: "已清空保存的查词记录。",
    translationCacheClearFailed: "清空查词记录失败。",
    audioCacheCleared: "已清空保存的朗读声音。",
    audioCacheClearFailed: "清空保存的朗读声音失败。",
    noSpeechContent: "没有可朗读内容。",
    wordSpeechUnavailable: "当前浏览器不能朗读单词。",
    playDone: (label: string, total: number) => `完成：${label}（${total} 遍）`,
    speakingWord: (label: string, played: number, total: number) => `正在朗读单词：${label}（${played}/${total}）`,
    tryingFallbackSpeech: (label: string, played: number, total: number) => `直接朗读没成功，正在尝试备用发音：${label}（${played}/${total}）`,
    wordSpeechFailed: (label: string, error: string) => `单词朗读失败：${label}（${error}）`,
    fullTextReady: "现在可以全文朗读了。",
    fullTextNotReady: "现在还不能全文朗读，安装全文朗读服务后会自动识别。",
    gatewayClosed: "全文朗读服务已关闭，需要时再打开。",
    checkingFullTextSpeech: "正在检查全文朗读...",
    gatewayOfficialDownloadOnly: "为了安全，请在官方网站下载全文朗读服务。",
    gatewayInstallerNotReady: "全文朗读服务安装文件还没有准备好，请稍后再试。",
    desktopDownloadOnly: "Windows 桌面版请在电脑浏览器中下载；手机上可以直接点单词听发音。",
    wordTapOfficialDownloadOnly: "为保证安全，请在官方网站上下载 WordTap。",
    wordTapInstallerNotReady: "WordTap 安装文件还没有准备好，请稍后再试。",
    fullTextSpeechUnavailable: "当前浏览器不能播放全文朗读。",
    fullTextSpeechWindowsOnly: "网页版，非 Windows 系统，暂时不支持全文朗读功能。",
    fullTextSpeechBrowserFallback: "全文朗读服务未启动，正在使用浏览器内置语音朗读。",
    speakingFullText: (label: string, played: number, total: number) => `正在朗读：${label}（${played}/${total}）`,
    cachedFullTextAudioFound: (label: string) => `已找到保存过的朗读声音：${label}`,
    preparingFullTextSpeech: (label: string) => `正在准备全文朗读：${label}`,
    generatingFullTextSpeech: (label: string) => `正在生成朗读声音：${label}`,
    fullTextSpeechFailed: (label: string, error: string) => `朗读失败：${label}（${error}）`,
    pasteEnglishFirst: "请先粘贴或输入英文文本。",
    noEnglishWordsFound: "没有找到英文单词。",
    wordsReady: (count: number) => `已准备好 ${count} 个可点读单词。`,
    lookingUpWord: (word: string) => `正在查词：${word}`,
    lookupFailed: (word: string) => `查词失败：${word}`,
    meaningMissingForWord: (word: string) => `暂时没有找到释义：${word}`,
    meaningFoundForWord: (word: string, source: string) => `已找到释义：${word}（${source}）`,
    pasteEnglishToRead: "请先粘贴或输入要朗读的英文文本。",
    stoppedSpeech: "已停止朗读。",
  },
  lookup: {
    loadingMeaning: "正在查找这个单词的释义...",
    missingMeaning: "未找到释义。",
    lookupFailedMeaning: "查词失败，请稍后再试。",
    wordWithoutMeaning: "这个单词还没有释义。",
    savedSource: "已保存",
    sourceLabels: {
      "memory-cache": "刚查过",
      "translation-cache": "已保存",
      "local-dictionary": "离线词典",
      "baidu-sug": "在线查词",
      fallback: "内置词典",
      missing: "未找到",
    },
  },
  dictionary: {
    unavailable: "查词暂时没准备好，仍可点单词听发音。",
  },
  diagnostics: {
    statuses: {
      pending: "检查中",
      ok: "可用",
      warn: "提醒",
      fail: "需要处理",
    },
    waiting: "等待检查...",
    timeout: "检查超时。",
    gatewayDisconnected: "暂时连不上。想全文朗读时，请先安装或打开全文朗读服务。",
    urlUnavailable: "暂时打不开，请稍后再试。",
    failed: "检查失败。",
    labels: {
      browserSpeech: "点词发音",
      studyRecords: "学习记录",
      translationCache: "查词记录",
      readingSettings: "阅读设置",
      dictionary: "查词功能",
      chineseMeaning: "中文释义",
      fullTextSpeech: "全文朗读",
      speechAndLookup: "朗读和查词",
      speechAudio: "朗读声音",
      onlineLookup: "在线查词",
      gateway: "全文朗读服务",
      gatewayDownload: "全文朗读服务下载",
      windowsDownload: "Windows 桌面版下载",
      studyRecordStorage: "保存学习记录",
      savedAudio: "保存的朗读声音",
    },
    browserSpeechUnsupported: "这个浏览器不能直接发音，会换一种方式播放单词发音。",
    browserSpeechReady: (count: number) => (count ? `可以发音，已找到 ${count} 个英文声音。` : "可以发音，声音列表可能稍后出现。"),
    studyRecordsReady: "单词、文本和释义都可以保存。",
    readingSettingsReady: "语速、遍数和声音选择可以保存。",
    dictionaryIncomplete: "查词可以用，但词条数量暂时显示不完整。",
    dictionaryReady: "可以查词。",
    chineseMeaningUnknown: "暂时没法确认中文释义。",
    chineseMeaningReady: "可以查到中文释义。",
    chineseMeaningMissing: "词典可以打开，但暂时没查到中文释义。",
    fullTextSpeechFailed: "全文朗读暂时不能用。",
    fullTextSpeechReady: "可以全文朗读了。",
    gatewayCapabilitiesPartial: "全文朗读服务已打开，但有些功能暂时不能用。",
    gatewayCapabilitiesReady: "全文朗读和在线查词都可用。",
    onlineLookupNoResult: "在线查词暂时没有返回结果。",
    onlineLookupReady: "在线查词可以返回释义。",
    onlineLookupNoMeaning: "在线查词能打开，但暂时没有返回释义。",
    speechAudioNoDetail: "全文朗读服务已打开，但还没有成功生成声音。",
    speechAudioWithDetail: (detail: string) => `全文朗读服务已打开，但还没有成功生成声音：${detail}`,
    speechAudioRequestedNoSound: "已请求朗读，但暂时没有声音。",
    speechAudioReady: "可以生成朗读声音。",
    gatewayReleaseIncomplete: "全文朗读服务下载信息不完整。",
    gatewayReleaseReady: "全文朗读服务下载信息可用。",
    downloadUnavailable: "下载地址暂时不可用。",
    downloadReady: "可以下载。",
    storageUnknown: "当前浏览器没法确认学习记录是否还能保存。",
    storageReady: "学习记录可以继续保存。",
    translationCacheSaved: (count: number) => `已保存 ${count} 条查词记录。`,
    translationCacheSummary: (count: number) => `${count} 条查词记录`,
    audioCacheSaved: (count: number, removed: number) => `已保存 ${count} 段朗读声音${removed ? `，已清理 ${removed} 段旧声音` : ""}。`,
    audioCacheSummary: (count: number) => `${count} 段朗读声音`,
    summaryUnavailable: "暂时无法读取",
    translationCacheClearedDetail: "保存的查词记录已清空。",
    audioCacheClearedDetail: "保存的朗读声音已清空。",
  },
  speechErrors: {
    gatewayNotStartedNeedle: "本地全文朗读服务未启动",
    unknown: "未知错误",
    autoplayBlocked: "浏览器不允许自动播放，请再点击一次朗读按钮",
    playbackInterrupted: "播放被打断了，请再点击一次朗读按钮",
    gatewayNotStarted: "全文朗读服务还没启动，请先安装或打开",
    gatewaySpeechFailed: "全文朗读暂时没有成功",
    browserSpeechUnsupported: "当前浏览器不能直接朗读。",
    browserSpeechNoResponse: "直接朗读没有响应。",
    browserSpeechFailed: (reason: string) => `直接朗读失败${reason}`,
    fallbackSpeechUnsupported: "当前浏览器不能播放备用发音。",
    fallbackSpeechNoResponse: "备用单词发音没有响应。",
    fallbackSpeechFailed: (reason: string) => `备用单词发音播放失败${reason}`,
    fallbackSpeechCanceled: "备用单词发音已取消。",
    fallbackSpeechFailedPlain: "备用单词发音播放失败。",
  },
  gatewaySpeech: {
    cancelled: "全文朗读已取消。",
    noContent: "没有可朗读内容。",
    gatewayNotStarted: "本地全文朗读服务未启动，请下载并运行 WordTap 全文朗读服务。",
    noAudioGenerated: "全文朗读没有生成声音。",
    audioPlaybackFailed: "全文朗读声音播放失败。",
    requestFailed: (status: number) => `全文朗读请求失败，HTTP ${status}。`,
  },
  historyStore: {
    textTooLong: (limit: string) => `文本超过 ${limit} 个字符，请先精简后再保存。`,
    missingMeaning: "未找到释义。",
    noImportRecords: "没有找到可导入的历史记录。",
    untitledArticle: "未命名文章",
    openDbFailed: "无法打开学习历史数据库。",
    indexedDbRequestFailed: "IndexedDB 请求失败。",
    writeFailed: "学习历史写入失败。",
    writeAborted: "学习历史写入被取消。",
  },
  voice: {
    enUs: "美式英语",
    enGb: "英式英语",
    enAu: "澳式英语",
    enCa: "加拿大英语",
    english: "英语",
    systemSource: "系统声音",
    browserSource: "浏览器声音",
  },
  template: {
    alertAria: "点词发音不可用",
    browserSpeechAlert: "当前浏览器不能直接发音，点击单词仍可查释义，并会自动尝试备用发音。",
    desktopDownloadAria: "WordTap Windows 桌面版下载",
    desktopDownloadCopy: "需要离线使用或全文朗读？可以下载 Windows 桌面版。",
    desktopUse: "电脑上使用",
    desktopDownload: "下载 Windows 桌面版",
    workspaceAria: "WordTap learning workspace",
    brandTagline: "粘贴英文，点词听读",
    mainNavAria: "主功能导航",
    navStudy: "开始学习",
    navReview: "我的单词",
    navDiagnostics: "遇到问题",
    navIpa: "国际音标",
    navNce: "新概念英语",
    currentWordTitle: "刚点的单词",
    translateModeLabel: "查词方式",
    rateLabel: "语速",
    repeatLabel: "遍数",
    repeatTimes: (count: number) => `${count} 遍`,
    wordVoiceLabel: "点词发音",
    autoVoice: "自动选择声音",
    fullTextVoiceLabel: "朗读声音",
    markLearnedLabel: "标出点过的单词",
    savedWordsStat: "保存单词",
    clickTotalStat: "累计点读",
    editorTitle: "正在阅读",
    saveArticle: "保存文章",
    readFullText: "全文朗读",
    stop: "停止",
    savedArticles: "保存过的文章",
    savedArticleOption: (title: string, count: number) => `${title}（${count} 次）`,
    deleteSelectedArticleTitle: "删除当前选中的文章",
    deleteArticle: "删除文章",
    gatewayGuide: "想让全文朗读，需要先安装全文朗读服务。装好后不用刷新页面，这里会自动变成可用。",
    installGateway: "安装全文朗读服务",
    sourcePlaceholder: "在这里粘贴或输入英文文本",
    readerTitle: "点词阅读",
    wordPopoverAria: "当前单词释义",
    reviewSummary: (wordTotal: number, clickTotal: number) => `已保存 ${wordTotal} 个单词，点读 ${clickTotal} 次`,
    refreshList: "刷新列表",
    importingWords: "导入中",
    importWords: "导入单词",
    exportWords: "导出单词",
    historySearchPlaceholder: "搜索学过的单词或中文意思",
    noMeaning: "暂无释义",
    speak: "朗读",
    deleteWord: "删除单词",
    recordCount: (count: number) => `${count} 次`,
    firstSeen: (time: string) => `首次 ${time}`,
    lastSeen: (time: string) => `最近 ${time}`,
    wordActionsAria: (word: string) => `单词操作：${word}`,
    diagnosticsSummaryEmpty: "检查发音、查词、保存和下载是否可用",
    diagnosticsRunning: "检查中",
    diagnosticsStart: "开始检查",
    diagnosticsUpdated: (time: string) => `最近检查：${time}`,
    clearSavedContent: "清理保存内容",
    savedAudioTitle: "保存的朗读声音",
    clearing: "清理中",
    clearAudio: "清空朗读声音",
    savedLookupTitle: "保存的查词记录",
    clearLookup: "清空查词记录",
    aboutTitle: "为认真读英文的人做的点读查词工具",
    aboutParagraphs: [
      "WordTap 面向正在阅读英文原文的人：学生、自学者、备考者、教师，以及每天要读英文资料的工作者。它不把学习拆成孤立的单词列表，而是让你在原文里点一下生词，听到发音，看到释义，再回到句子继续理解。",
      "适合精读一段英文、跟读一段材料、检查考试阅读里的生词，也适合把平时遇到的英文邮件、文档或网页片段放进来慢慢读。核心体验是少切换、少打断，让注意力留在这段英文上。",
    ],
    quietTitle: "安静、直接、不过度打扰",
    quietParagraphs: [
      "很多英语学习工具会把你带去另一个页面、另一个弹窗、另一个任务。WordTap 的取向相反：文本就在眼前，单词就在原句里，释义和朗读只服务于当前阅读，不抢走学习节奏。",
      "你粘贴的内容默认只保存在这台设备上，用起来更安心。它更像一张安静的阅读桌：打开、粘贴、点读、理解，然后继续往下读。",
    ],
    audienceCards: [
      {
        title: "读英文的人",
        body: "适合读英语新闻、短文、教材、论文摘要、技术文档、考试阅读和英文邮件的人。你关心的是读懂这一段，而不是被查词流程拖走。",
      },
      {
        title: "练听读的人",
        body: "单词不仅要看懂，也要听得出、读得顺。点击单词听发音，调整语速和遍数，可以把查词顺手变成一次轻量跟读。",
      },
      {
        title: "带学生的人",
        body: "老师、家长或学习搭子可以把一段材料放进来，带着学习者逐词点读、逐句理解，让查词和朗读都围绕同一篇文本展开。",
      },
    ],
    footerAria: "网站底部信息",
    feedbackLabel: "意见反馈：",
    icp: "粤ICP备17134686号-3",
  },
  ipa: {
    title: "国际音标",
    subtitle: "点击音标卡片即可听发音",
    vowels: "元音",
    longVowels: "长元音",
    shortVowels: "短元音",
    diphthongs: "双元音",
    consonants: "辅音",
    voicelessConsonants: "清辅音",
    voicedConsonants: "浊辅音",
    sourceYp: "英语兔",
    sourceXdf: "新东方",
    sourceMp3: "基础发音",
  },
} as const;
